# This config uses the Automatic Test Mode to automatically adjust the Curve Optimizer values
# on Ryzen processors after an error has occurred
# It sets the Curve Optimizer values to the minimum value and will make it less aggressive
# step by step when an error or a crash occurs
#
# The test now runs until every core has found a good value (or until the maxValue has been reached
# for a core), so expect this to take many hours
# The found values are permanently stored in the "*_automode-results.txt" file in the logs directory
#
# Author: sp00n


[General]
stressTestProgram = YCRUNCHER
runtimePerCore = auto
coreTestOrder = Default
numberOfThreads = 1

# Note: maxIterations is not used in the Automatic Test Mode


[yCruncher]
mode = auto                 # This chooses the binary automatically, e.g. "19-ZN2 ~ Kagari" for Ryzen 5000 or "24-ZN5 ~ Komari" for Ryzen 9000
tests = SFTv4, FFTv4, N63   # Limit the tests to stressful ones
#tests = BKT, BBP, SFTv4, SNT, SVT, FFTv4, N63, VT3   # These would be all of the available tests

# 20 seconds per test
testDuration = 20


[AutomaticTestMode]
enableAutomaticAdjustment = 1
startValues = Minimum       # Automatically select the minimum possible Curve Optimizer value (-30 for Ryzen 5000, -50 Ryzen 7000/8000/9000)
maxValue = 0                # Do not go above Curve Optimizer value of 0
incrementBy = 1             # Adjust the Curve Optimizer value by 1 after an error


# A core needs to complete this many test runs in a row without an error before its Curve Optimizer
# value is considered good and the core is not tested anymore
# Higher values give you more confidence, but the test will take proportionally longer
passesToConfirmCoreValue = 3


# If you already know the good value for some of the cores, you can enter them here
# These cores will then not be tested at all
# You can find a ready to use line at the end of the "*_automode-results.txt" file of a previous run
#knownGoodValues = 3:-25, 7:-18


# Set the Curve Optimizer value only for the currently tested core
# All other cores will be set to 0, to avoid any possible interference
setVoltageOnlyForTestedCore = 1


# Setting to try to automatically resume after a crash / hard reboot
# For this to work properly, Auto Logon should be activated
# Otherwise the computer will just idle at the logon screen after a crash
# See https://learn.microsoft.com/en-us/sysinternals/downloads/autologon
# and https://learn.microsoft.com/en-us/troubleshoot/windows-server/user-profiles-and-logon/turn-on-automatic-logon
enableResumeAfterUnexpectedExit = 1


# We want to create a System Restore Point before starting the whole process
# Crashes can cause a corrupted Windows installation, and a Restore Point can help fix that
createSystemRestorePoint = 1


# Don't ask for the creation of a System Restore Point, just do it
# It will only do so at the beginning, not during the process, and only once within 24 hours
askForSystemRestorePointCreation = 0